/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#571bc1",
        "surface-variant": "#2d3449",
        "tertiary": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "surface-dim": "#0b1326",
        "surface-container-high": "#222a3d",
        "primary-fixed-dim": "#adc6ff",
        "on-primary-container": "#00285d",
        "surface-tint": "#adc6ff",
        "inverse-primary": "#005ac2",
        "on-tertiary": "#003824",
        "background": "#0b1326",
        "outline-variant": "#424754",
        "on-tertiary-fixed-variant": "#005236",
        "primary-container": "#4d8eff",
        "on-background": "#dae2fd",
        "secondary": "#d0bcff",
        "on-error-container": "#ffdad6",
        "surface-bright": "#31394d",
        "on-secondary-fixed-variant": "#5516be",
        "primary": "#adc6ff",
        "surface": "#0b1326",
        "surface-container-low": "#131b2e",
        "surface-container-lowest": "#060e20",
        "on-surface": "#dae2fd",
        "on-secondary-container": "#c4abff",
        "secondary-fixed-dim": "#d0bcff",
        "tertiary-container": "#00a572",
        "surface-container-highest": "#2d3449",
        "error-container": "#93000a",
        "on-secondary": "#3c0091",
        "on-surface-variant": "#c2c6d6",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#23005c",
        "tertiary-fixed-dim": "#4edea3",
        "on-primary-fixed": "#001a42",
        "outline": "#8c909f",
        "inverse-on-surface": "#283044",
        "primary-fixed": "#d8e2ff",
        "secondary-fixed": "#e9ddff",
        "surface-container": "#171f33",
        "on-tertiary-container": "#00311f",
        "tertiary-fixed": "#6ffbbe",
        "on-error": "#690005",
        "on-primary": "#002e6a",
        "inverse-surface": "#dae2fd",
        "on-primary-fixed-variant": "#004395"
      },
      borderRadius: {
        "sm": "0.125rem",
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "panel-gap": "1px",
        "margin-mobile": "16px",
        "margin-desktop": "24px",
        "gutter": "16px"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "label-caps": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "code-sm": ["JetBrains Mono"]
      },
      fontSize: {
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "code-md": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "code-sm": ["11px", { "lineHeight": "16px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
